version: 2
jobs:
  build:
    docker:
    - image: circleci/php:7.1-browsers
    working_directory: ~/repo

    steps:
    - checkout
    - run: composer install -n --prefer-dist
    - run: phpunit
  deploy:
    docker:
    - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
